In [2]:
from IPython.display import display, Latex
from IPython.core.display import HTML
%reset -f
%matplotlib inline
%autosave 300
from matplotlib.pylab import *

Autosaving every 300 seconds


# Manipulation de base sur les tableaux
En important la librairie matplotlib, la librairie numpy est également chargée. Elle permet la manipulation de tableaux et contient des opérations empruntées aux opérations matricielles mathématiques.

## Définition, modification, opérations

On définit des tableaux comme suit, soit par remplissage de tous les coefficients, soit par des tableaux de 1 (ones) ou 0 (zeros).

In [3]:
a=array([[1,2],[3,4]])
b=5*ones((2,2))
print('a=',a)
print('b=',b)
print('a+b=',a+b)

a= [[1 2]
 [3 4]]
b= [[5. 5.]
 [5. 5.]]
a+b= [[6. 7.]
 [8. 9.]]


On profite du tableau "zeros" pour intialiser un tableau à la taille souhaitée et modifier les coefficients en position ligne colonne de notre choix. Attention, les indices démarrent à 0 et non 1.

In [4]:
c=zeros((3,3))
c[2,1]=2
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 2. 0.]]


On peut également affecter un sous-tableau d'un tableau.

In [5]:
d=zeros((3,3))
d[0:2,0:2]=a
print(d)

[[1. 2. 0.]
 [3. 4. 0.]
 [0. 0. 0.]]


On peut effectuer des produit composantes par composantes:

In [6]:
print(d*d)

[[ 1.  4.  0.]
 [ 9. 16.  0.]
 [ 0.  0.  0.]]


La commande "arange" permet de créer sous forme de vecteur numpy l'équivalent de l'itérateur "range". Il est possible de modifier la forme du tableau pour le transformer (reshape) en un tableau du même nombre d'éléments mais avec un nombre de ligne et colonne différent. Notez bien l'ordre dans lequel sont rangés les éléments.

In [7]:
vec=arange(3,21,2)
print(vec)
mat3x3=vec.reshape(3,3)
print("matrie 3x3 : ")
print(mat3x3)
print("mis en une unique colonne : ")
print(mat3x3.reshape(9,1))
print("mis en une unique ligne : ")
print(mat3x3.reshape(1,9))
print("reshape après transposition, l'ordre est bousculé :")
print(mat3x3.T.reshape(1,9))

[ 3  5  7  9 11 13 15 17 19]
matrie 3x3 : 
[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]
mis en une unique colonne : 
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]
mis en une unique ligne : 
[[ 3  5  7  9 11 13 15 17 19]]
reshape après transposition, l'ordre est bousculé :
[[ 3  9 15  5 11 17  7 13 19]]


On peut utiliser la commande "diag" afin de positionner en diagonale, un vecteur ou un sous-tableau dans un tableau dont on précise la taille. Les autres coefficients non précisés etant nuls. On choisit de combien on décale la diagonale par rapport à la diagonale principale.

In [8]:
vec=arange(1,10)
M=diag(vec,1)+diag(ones(9),-1)
print(M)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


## Produit matriciel
La multiplication matricielle utilise la fonction dot:

In [9]:
print(dot(d,d))
print("une variante d'écriture pour le même résultat:")
print(d.dot(d))


[[ 7. 10.  0.]
 [15. 22.  0.]
 [ 0.  0.  0.]]
une variante d'écriture pour le même résultat:
[[ 7. 10.  0.]
 [15. 22.  0.]
 [ 0.  0.  0.]]


On peut également utiliser l'opérateur "@" qui signifie produit matriciel entre deux tableaux de taille compatible:

In [10]:
print(d@d)

[[ 7. 10.  0.]
 [15. 22.  0.]
 [ 0.  0.  0.]]


Le produit scalaire de deux vecteurs n'est autre que le produit matriciel à une transposition près (produit d'un vecteur ligne par un vecteur colonne). 

Le produit matrice vecteur n'est rien d'autre qu'un produit matriciel. Exemples:

In [13]:
vec=array([[1],[2],[3]])
print("vecteur colonne ou tableau 3 lignes 1 colonne")
print(vec)
vectrans=vec.T
print("son transposé:",vectrans)
print("2 produits possibles:")
print(vec@vectrans)
print("le deuxième")
print(vectrans@vec)
print("produit matrice vecteur:")
print(d@vec)



vecteur colonne ou tableau 3 lignes 1 colonne
[[1]
 [2]
 [3]]
son transposé: [[1 2 3]]
2 produits possibles:
[[1 2 3]
 [2 4 6]
 [3 6 9]]
le deuxième
[[14]]
produit matrice vecteur:
[[ 5.]
 [11.]
 [ 0.]]


Attention aux tableaux qui ne sont qu'une conversion d'une liste de nombres et non une liste de liste de nombres. Dans ce cas, la notion de ligne ou colonne est ambigue. La transposée n'agit pas, le produit dot ou @ a un sens de produit scalaire.

In [14]:
a=array([1,2,3])
print(a.dot(a),a@a)
print("a=",a)
print("a.T=",a.T)

14 14
a= [1 2 3]
a.T= [1 2 3]


## Exercices
Coder et afficher les calculs suivants:
$$
\left (\matrix{1&2&1\\
2&1&1\\
1&1&1}\right)\left (\matrix{1\\
2\\
1}\right)
$$
$$
\left (\matrix{
1&0&0&0&0&0&0\\
0&1&0&0&0&0&0\\
0&0&2&2&1&0&0\\
0&0&2&2&1&0&0\\
0&0&1&1&2&0&0\\
0&0&0&0&0&1&0\\
0&0&0&0&0&0&1\\
}\right)+
\left (\matrix{
1&0&0&0&0&0&0\\
0&1&0&0&0&0&0\\
0&0&1&0&0&0&0\\
0&0&0&1&0&0&0\\
0&0&0&0&1&0&0\\
0&0&0&0&0&1&0\\
0&0&0&0&0&0&1\\
}\right)+
\left (\matrix{
0&0&0&0&0&0&1\\
0&0&0&0&0&1&0\\
0&0&0&0&1&0&0\\
0&0&0&1&0&0&0\\
0&0&1&0&0&0&0\\
0&1&0&0&0&0&0\\
1&0&0&0&0&0&0\\
}\right)
$$

Construire et afficher la matrice de taille 9x9 qui ne contient que des zéros sauf des $-4$ sur la deuxième sous-diagonale.

Calculer la somme des carrés des 60 premiers entiers non nuls à l'aide d'un vecteur et de la commande "dot". Calculer la somme de ces entiers toujours à l'aide de vecteurs et de "dot".

## Factorisation PLU
On peut factoriser, sous quelques hypothèses, une matrice  $A$ sous la forme $A=PLU$ où $L$ (lower) est une matrice triangulaire inférieure avec des $1$ sur la diagonale, $U$ (upper) une matrice triangulaire supérieure et $P$ une matrice de permutation. Cette factorisation correspond aux opérations de transformation de la matrice par la méthode de Gauss avec pivot.  Le but étant de résoudre alors un système linéaire dont $A$ est la matrice qu'on supposera alors carrée. L'hypothèse $A$ inversible suffit pour assurer cette factorisation. La méthode de Gauss (sans pivot, $P=Id$) s'applique  dès lors que toutes les sous-matrices de $A$ sont inversibles.

In [16]:
from scipy import linalg
#U=triu([[1,2,3],[4,5,6],[7,8,9]])
#L=tril([[1,2,3],[4,5,6],[7,8,9]])
A=array([[1,2,3],[4,5,6],[7,8,10]])
P,L,U=linalg.lu(A)
print(P,L,U)
print("verification",P.dot(L.dot(U)))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] [[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]
verification [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]


## Exercice
En n'utilisant que la transposition et un algorithme de résolution de système triangulaire (inférieur ou supérieur) que vous coderez avec une seule boucle, résoudre le système linéaire $Ax=b$ à partir de $P$, $L$, $U$ de la factorisation $A=PLU$. Pour vérifier votre calcul, cet outil est déjà codé dans scipy avec la commande suivante:

In [17]:
#Forme compactee de la factorisation PLU
lu=linalg.lu_factor(A)
#appel de la resolution du système depuis la factorisation lu
b=ones((3,1))
x=linalg.lu_solve(lu,b)
print("x est le vecteur : ")
print(x)
print("on vérifie Ax=b : ")
print(A@x)

# ECRIRE VOTRE PROPRE ALGO QUI TROUVE x depuis P,L,U,b

x est le vecteur : 
[[-1.00000000e+00]
 [ 1.00000000e+00]
 [ 3.33066907e-16]]
on vérifie Ax=b : 
[[1.]
 [1.]
 [1.]]


In [65]:
#sans savoir ce que scipy choisit comme solveur, 
#il existe la commande de résolution de systeme linéaire
print(linalg.solve(A,b))

[[-1.00000000e+00]
 [ 1.00000000e+00]
 [ 3.33066907e-16]]


## Valeurs propres et vecteurs propres
La commande "eig" permet de disposer des valeurs propres et des vecteurs propres associés. La commande "inv" permet d'inverser la matrice. On ne s'en sert pas pour résoudre un système linéaire, c'est beaucoup trop cher en calcul! 


In [66]:
eig(A)

(array([16.70749332, -0.90574018,  0.19824686]),
 array([[-0.22351336, -0.86584578,  0.27829649],
        [-0.50394563,  0.0856512 , -0.8318468 ],
        [-0.83431444,  0.4929249 ,  0.48018951]]))

In [68]:
inv(A)

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

## Exercice

Calculer les valeurs propres de la matrice $A$ de taille $(20,20)$ constituée de $3$ sur la diagonale principale, de $-1$ sur la diagonale supérieure et inférieure.

Pourquoi la matrice est inversible? Les valeurs propres sont elles réelles et strictement positives? 

Indication pour la preuve: commencer par vérifier que si $x$ est vecteur propre de $A$ pour la valeur propre $0$, les valeurs extrémales des composantes de $x$ sont nécessairement nulles.

.... Rédigez!

## Exercices
Dans les exercices qui suivent, la solution numérique proposée ne doit faire appel à aucune boucle, mais s'appuyer sur des produits matriciels ou scalaires entre tableaux de type array (du module numpy)

1- Calculer
$$
\sum_{i=1}^{49}(-u_{i-1}+2u_i-u_{i+1})u_i-f(u_i)u_i,
$$
où $U=(u_0,u_1,\cdots,u_{50})$ est donné par
$$
u_i=\sin(i)\frac {i^2}{1+i^2},
$$
où $f$ est la fonction définie par
$$
f(x)=\sin(x)\cos(x^2).
$$
2- On se donne $U=(u_0,u_1,\cdots,u_{100})$, $V=(v,v_1,\cdots,v_{100})$ avec,
$$
u_i=\sin(i)\frac {i^2}{1+i^2},~v_i=cos(i)i.
$$
Calculer
$$
\sum_{i=0,~i\text{ pair}}^{100}u_iv_{100-i},
$$
$$
\sum_{i=0,~i\text{ impair}}^{97}u_iv_{i+3}.
$$